### ISSUE TITLE
Automatic detection of application mapping

### ISSUE THREAD

**Issue by MartinMystikJonas** [efabrica-team/phpstan-latte#27]
Maybe add option applicationConfig to specify config file to load mapping config from? Just parse it as .neon and load application.mapping key?

**Comment by lulco** [comment]
I think this is not enough (at least for my / our apps). We have mapping in core config.neon in vendor dir and it is merged with all other modules' configs. So I think we should cover this in docs and tell users they should move mapping to parameters and include some special file where this parameter is loaded from Container.

**Comment by MartinMystikJonas** [comment]
Agreed. So probably just `mappingLoader` option to specify script that will load config?

**Comment by lulco** [comment]
I have to think about it. My idea was to add only parameters and let it to developers how they are filled - manually or they create some service / included file which returns them.

In our company we use custom includes for this https://github.com/dev-efabrica/efabrica-phpstan-config/tree/phpstan-latte/includes/nette-app

**Comment by lulco** [comment]
I would just add to docs with example, something like this:

create file mapping.neon with this content 
```neon
parameters:
    mapping:
        *: FooBar\Baz\*Presenter
```
include it to your application config.neon and also to phpstan.neon and use %mapping% in corresponding places

**Comment by spaze** [comment]
> I would just add to docs with example, something like this:
> 
> create file mapping.neon with this content
> 
> ```neon
> parameters:
>     mapping:
>         *: FooBar\Baz\*Presenter
> ```
> 
> include it to your application config.neon and also to phpstan.neon and use %mapping% in corresponding places

Btw, this doesn't seem to work for me. I'm getting

> Invalid configuration:
Unexpected item 'parameters › mapping'.

Which I think is because there's no `mapping` key specified in `extension.neon`. But not sure adding it would be the correct way to deal with this as the key in `mapping.neon` would need to be named exactly like this but what if my app already uses the key for something else... One option would be to name the key say `applicationMapping` and require that key but what if want to name the key `chuckNorris` for example 🤣

**Comment by lulco** [comment]
Yeah, there is scheme for parameters. I forgot :)) I wanted to use mapping.neon as shared file for both - application and phpstan-latte :(

Ok, but this should work:

mapping.neon should contain:
```neon
parameters:
    latte:
        applicationMapping:
            *: FooBar\Baz\*Presenter
```

include it in phpstan.neon and also in application config.

in phpstan everything is done. In application config do last change:
```neon
application:
    mapping: %latte.applicationMapping%
```

**Comment by MartinMystikJonas** [comment]
I think I like your approach with .php configs for PHPStan more that this.

**Comment by lulco** [comment]
It's up to user. There are at least 3 options to do that :)

**Comment by lulco** [comment]
Btw my php config also includes that user have to move mapping to parameters and then read it from container

**Comment by spaze** [comment]
> Yeah, there is scheme for parameters. I forgot :)) I wanted to use mapping.neon as shared file for both - application and phpstan-latte :(
> 
> Ok, but this should work:
> 
> mapping.neon should contain:
> 
> ```neon
> parameters:
>     latte:
>         applicationMapping:
>             *: FooBar\Baz\*Presenter
> ```
> 
> include it in phpstan.neon and also in application config.
> 
> in phpstan everything is done. In application config do last change:
> 
> ```neon
> application:
>     mapping: %latte.applicationMapping%
> ```

That's one option I intentionally left out and avoided. If you look at it, without any prior phpstan-latte extension knowledge, it is somewhat confusing. Looking at `mapping.neon`: why Latte needs any mapping? Looking at the whole thing why is a "dev" thing (the PHPStan extension) config driving the app mapping? As much as I don't like it, and given there are no other ways, I'd just copy & paste it.

**Comment by lulco** [comment]
I see. Than copy or use php included config which reads it from container. 

Important note - if you use robot loader, you will probably face the issue with lock “ Unable to acquire exclusive lock on file”. It’s because bootstrap is included more than once at the time. I had to “cache” it https://github.com/dev-efabrica/efabrica-phpstan-config/blob/phpstan-latte/includes/nette-app/bootstrap.php

**Comment by mabar** [comment]
If you want it perfect, make it use IPresenterFactory service.
There are few extensions in the wild which allow more customized mapping, e.g. replacing one presenter class with other for the same mapping string. I even went so far that I am using presenter classes directly, without clasical mapping.

**Comment by lulco** [comment]
> If you want it perfect, make it use IPresenterFactory service.

We are using method format* and unformat*
to detect which presenter is used in links.

> There are few extensions in the wild which allow more customized mapping, e.g. replacing one presenter class with other for the same mapping string.

> I even went so far that I am using presenter classes directly, without clasical mapping.

Can you elaborate this and show some example how it looks in latte?

**Comment by mabar** [comment]
> We are using method format* and unformat*

That is an internal default implementation that may be completely overriden. Also be aware unformatPresenterClass is deprecated and there is no replacement for it

> Can you elaborate this and show some example how it looks in latte?

It's currently not documented so hopefully [tests](https://github.com/orisai/nette-application/blob/76b713b6e985ce0ef0849077ae252319d7da5b61/tests/Unit/Mapping/DefaultPresenterFactoryTest.php#L139-L182) will help you get a better picture.

In Latte it may look like this: `{plink App\Home\Admin\HomePresenter:default}` - refering to class `App\Home\Admin\HomePresenter` directly

Mapping could also completely overriden different mapping or class. Following config says "when mapped string `OriCMF\Home\Admin\HomePresenter` is requested, return class `App\Home\Admin\HomePresenter` instead"

```neon
application:
	mapping:
		OriCMF\Home\Admin\HomePresenter: App\Home\Admin\HomePresenter
```

Also `Mapped:String` to class mapping works this way, you could map string to any class. Originally from [nepada/presenter-mapping](https://github.com/nepada/presenter-mapping#presenter-class-mapping) package.

```neon
application:
    mapping:
        'Foo:Bar:Baz': FooBar\BazPresenter
```

And there is also [librette/presenter-factory](https://github.com/JohnyRicio/presenter-factory) which allows mapping two namespaces two one module (my coworker unfortunatelly uses it because he historically has App namespace in vendor packages)

The point is - if it should work with any setup, it has to use IPresenterFactory service and method getPresenterClass()

**Comment by MartinMystikJonas** [comment]
I guess we can add presenterFactoryBootstrap same way as engineBootstrap.

**Comment by lulco** [comment]
Agree, I’ll try to implement it
