### ISSUE TITLE
Parameter #1 $s of static method Latte\Runtime\Filters::escapeCss() expects string, float given. 

### ISSUE THREAD

**Issue by lulco** [efabrica-team/phpstan-latte#298]
Latte:
```latte
{var $top = round(456 / 10)};
<style>
    .foo-bar {
        top: {$top}%;
    }
</style>
```
PHP:
```php
echo \Latte\Runtime\Filters::escapeCss($objectTop);
```

We could  add cast to string 
```php
echo \Latte\Runtime\Filters::escapeCss((string)$objectTop);
```
or ignore this error again.

Adding cast can lead to error from strict rules: "Casting to string something which is already string" or "Cannot cast mixed to string" etc.

There are several methods like this and also there can be several types of parameter (float, int, Stringable, HtmlStringable etc.).

I don't get it why there is php doc with type string, but then input is casted to string

```php
/**
  * Escapes string for use inside CSS template.
  * @param  string  $s  plain text
  * @return string CSS
  */
public static function escapeCss($s): string
{
	// http://www.w3.org/TR/2006/WD-CSS21-20060411/syndata.html#q6
	return addcslashes((string) $s, "\x00..\x1F!\"#$%&'()*+,./:;<=>?@[\\]^`{|}~");
}
```

**Comment by lulco** [comment]
We can try concat with empty string

**Comment by MartinMystikJonas** [comment]
I would either:

1)  add cast to string and ignore all useless casts in compiled templates (they probably would not be part or latte code and there is no way user can fix them if it appears in compiled code)
2) simply ignore this type of error for all escape methods of Filters and all known stribgable inputs
3) let it be it can be fixed in template

I would for 2 as easiest and good enough
